
version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - app-network

  service_1:
    build: ./service_1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service_2:
    build: ./service_2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
